### ISSUE TITLE
topic modeling example code error

### ISSUE THREAD

**Issue by Kyuseol** [youngwoos/Doit_textmining#1]
슬라이드 16의 코드 수정이 필요합니다.

`filter(str_count(reply, boundary("word") >= 3))`

다음과 같이 수정해야 합니다.(괄호 위치 수정)
`filter(str_count(reply, boundary("word")) >= 3)`

**Comment by youngwoos** [comment]
@Kyuseol 알려주셔서 감사합니다. 반영하여 수정했습니다.
https://youngwoos.github.io/Doit_textmining/06/06-topicModeling.html#16
